In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as  plt
import seaborn as sns

In [3]:
df = pd.read_csv("Fake_news_Dataset.csv")
df.head()

,Unnamed: 0,title,text,label
0,0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,No comment is expected from Barack Obama Membe...,1
1,1,NaN,Did they post their votes for Hillary already?,1
2,2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...,"Now, most of the demonstrators gathered last ...",1
3,3,"Bobby Jindal, raised Hindu, uses story of Chri...",A dozen politically active pastors came here f...,0
4,4,SATAN 2: Russia unvelis an image of its terrif...,"The RS-28 Sarmat missile, dubbed Satan 2, will...",1

In [4]:
df.shape

(72134, 4)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72134 entries, 0 to 72133
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  72134 non-null  int64
 1   title       71576 non-null  object
 2   text        72095 non-null  object
 3   label       72134 non-null  int64
dtypes: int64(2), object(2)
memory usage: 2.2+ MB

In [6]:
df.describe()

         Unnamed: 0         label
count  72134.000000  72134.000000
mean   36066.500000      0.514404
std    20823.436496      0.499796
min        0.000000      0.000000
25%    18033.250000      0.000000
50%    36066.500000      1.000000
75%    54099.750000      1.000000
max    72133.000000      1.000000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72134 entries, 0 to 72133
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  72134 non-null  int64
 1   title       71576 non-null  object
 2   text        72095 non-null  object
 3   label       72134 non-null  int64
dtypes: int64(2), object(2)
memory usage: 2.2+ MB

In [8]:
df.columns

Index(['Unnamed: 0', 'title', 'text', 'label'], dtype='object')

In [9]:
df.isnull().sum()

Unnamed: 0      0
title         558
text           39
label           0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.drop('Unnamed: 0',axis=1,inplace=True)

In [12]:
df = df.dropna(subset=['title','text'])

print(df.isnull().sum())

title    0
text     0
label    0
dtype: int64

In [13]:
df.shape

(71537, 3)

In [14]:
df['label'].value_counts()

label
1    36509
0    35028
Name: count, dtype: int64

In [15]:
df['label'].value_counts(normalize=True)

label
1    0.510351
0    0.489649
Name: proportion, dtype: float64

In [16]:
df['content'] = df['title']+" "+df['text']

In [17]:
df[['title', 'text', 'content']].head()

,title,text,content
0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,No comment is expected from Barack Obama Membe...,LAW ENFORCEMENT ON HIGH ALERT Following Threat...
2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...,"Now, most of the demonstrators gathered last ...",UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...
3,"Bobby Jindal, raised Hindu, uses story of Chri...",A dozen politically active pastors came here f...,"Bobby Jindal, raised Hindu, uses story of Chri..."
4,SATAN 2: Russia unvelis an image of its terrif...,"The RS-28 Sarmat missile, dubbed Satan 2, will...",SATAN 2: Russia unvelis an image of its terrif...
5,About Time! Christian Group Sues Amazon and SP...,All we can say on this one is it s about time ...,About Time! Christian Group Sues Amazon and SP...

In [18]:
df.head()

,title,text,label,content
0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,No comment is expected from Barack Obama Membe...,1,LAW ENFORCEMENT ON HIGH ALERT Following Threat...
2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...,"Now, most of the demonstrators gathered last ...",1,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...
3,"Bobby Jindal, raised Hindu, uses story of Chri...",A dozen politically active pastors came here f...,0,"Bobby Jindal, raised Hindu, uses story of Chri..."
4,SATAN 2: Russia unvelis an image of its terrif...,"The RS-28 Sarmat missile, dubbed Satan 2, will...",1,SATAN 2: Russia unvelis an image of its terrif...
5,About Time! Christian Group Sues Amazon and SP...,All we can say on this one is it s about time ...,1,About Time! Christian Group Sues Amazon and SP...

In [19]:
import re
import string

def clean_text(text):
    text = text.lower()  # lowercase
    text = re.sub(r"http\S+|www\S+|https\S+", "", text)  # remove URLs
    text = re.sub(r"\d+", "", text)  # remove numbers
    text = text.translate(str.maketrans("", "", string.punctuation))  # remove punctuation
    text = re.sub(r"\s+", " ", text).strip()  # remove extra spaces
    return text

# Apply cleaning on content column
df['clean_content'] = df['content'].apply(clean_text)

# Check results
df[['content', 'clean_content']].head()

,content,clean_content
0,LAW ENFORCEMENT ON HIGH ALERT Following Threat...,law enforcement on high alert following threat...
2,UNBELIEVABLE! OBAMA’S ATTORNEY GENERAL SAYS MO...,unbelievable obama’s attorney general says mos...
3,"Bobby Jindal, raised Hindu, uses story of Chri...",bobby jindal raised hindu uses story of christ...
4,SATAN 2: Russia unvelis an image of its terrif...,satan russia unvelis an image of its terrifyin...
5,About Time! Christian Group Sues Amazon and SP...,about time christian group sues amazon and spl...

In [20]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

# Features and target
X = df['clean_content']
y = df['label']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# TF-IDF Vectorizer
tfidf = TfidfVectorizer(max_features=5000)

# Fit on training data and transform both train and test
X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

print("Train TF-IDF shape:", X_train_tfidf.shape)
print("Test TF-IDF shape:", X_test_tfidf.shape)

Train TF-IDF shape: (57229, 5000)
Test TF-IDF shape: (14308, 5000)

In [21]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [22]:
nv = MultinomialNB()
nv.fit(X_train_tfidf, y_train)

MultinomialNB()

In [23]:
y_pred_nv = nv.predict(X_test_tfidf)
y_pred_nv

array([1, 1, 1, ..., 0, 0, 0], shape=(14308,))

In [24]:
nv.score(X_test_tfidf, y_test)

0.8412776069331842

In [25]:
print("Accuracy of Naive Bayes: ",accuracy_score(y_test,y_pred_nv))

Accuracy of Naive Bayes:  0.8412776069331842

In [26]:
print("\nClassification Report of Naive Bayes: \n", classification_report(y_test, y_pred_nv))
print("\nConfusion Matrix of Naive Bayes: \n", confusion_matrix(y_test, y_pred_nv))

Classification Report of Naive Bayes:
               precision    recall  f1-score   support

           0       0.86      0.81      0.83      7006
           1       0.83      0.87      0.85      7302

    accuracy                           0.84     14308
   macro avg       0.84      0.84      0.84     14308
weighted avg       0.84      0.84      0.84     14308


Confusion Matrix of Naive Bayes:
 [[5691 1315]
 [ 956 6346]]

In [27]:
lr = LogisticRegression()
lr.fit(X_train_tfidf,y_train)

LogisticRegression()

In [28]:
y_pred_lr= lr.predict(X_test_tfidf)
y_pred_lr

array([1, 1, 0, ..., 0, 0, 0], shape=(14308,))

In [29]:
lr.score(X_test_tfidf,y_test)

0.9451355884819681

In [30]:
print("Accuracy of Logistic Regression: ",accuracy_score(y_test,y_pred_lr))

Accuracy of Logistic Regression:  0.9451355884819681

In [31]:
print("\nClassification Report of Logistic Regression: \n", classification_report(y_test, y_pred_lr))
print("\nConfusion Matrix of Logistic Regression: \n", confusion_matrix(y_test, y_pred_lr))

Classification Report of Logistic Regression:
               precision    recall  f1-score   support

           0       0.95      0.93      0.94      7006
           1       0.94      0.96      0.95      7302

    accuracy                           0.95     14308
   macro avg       0.95      0.94      0.95     14308
weighted avg       0.95      0.95      0.95     14308


Confusion Matrix of Logistic Regression:
 [[6543  463]
 [ 322 6980]]

In [35]:
import joblib

# Save Logistic Regression model
joblib.dump(lr, "fake_news_model.pkl")

# Save TF-IDF vectorizer
joblib.dump(tfidf, "tfidf_vectorizer.pkl")

print("Model and Vectorizer saved successfully!")

Model and Vectorizer saved successfully!

In [36]:
loaded_model = joblib.load("fake_news_model.pkl")
loaded_tfidf = joblib.load("tfidf_vectorizer.pkl")

In [42]:
def predict_news(news_text):
    news_text = clean_text(news_text)   # use your same cleaning function
    vector = tfidf.transform([news_text])
    prediction = lr.predict(vector)[0]
    
    if prediction == 1:
        return "REAL NEWS"
    else:
        return "FAKE NEWS"

In [43]:
sample_news = "Government announces new scheme for students in India."
print(predict_news(sample_news))

REAL NEWS