In [86]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [87]:
df = pd.read_csv("matches.csv")
df.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [88]:
df.shape

(1095, 20)

In [89]:
df.columns

Index(['id', 'season', 'city', 'date', 'match_type', 'player_of_match',
       'venue', 'team1', 'team2', 'toss_winner', 'toss_decision', 'winner',
       'result', 'result_margin', 'target_runs', 'target_overs', 'super_over',
       'method', 'umpire1', 'umpire2'],
      dtype='object')

In [90]:
df.describe()

                 id  result_margin  target_runs  target_overs
count  1.095000e+03    1076.000000  1092.000000   1092.000000
mean   9.048283e+05      17.259294   165.684066     19.759341
std    3.677402e+05      21.787444    33.427048      1.581108
min    3.359820e+05       1.000000    43.000000      5.000000
25%    5.483315e+05       6.000000   146.000000     20.000000
50%    9.809610e+05       8.000000   166.000000     20.000000
75%    1.254062e+06      20.000000   187.000000     20.000000
max    1.426312e+06     146.000000   288.000000     20.000000

In [91]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   object
 2   city             1044 non-null   object
 3   date             1095 non-null   object
 4   match_type       1095 non-null   object
 5   player_of_match  1090 non-null   object
 6   venue            1095 non-null   object
 7   team1            1095 non-null   object
 8   team2            1095 non-null   object
 9   toss_winner      1095 non-null   object
 10  toss_decision    1095 non-null   object
 11  winner           1090 non-null   object
 12  result           1095 non-null   object
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   object
 17  method           21 non-null     object
 18  umpire1          1095 non-null   object
 19  umpire2          1095 non-null   object
dtypes: float64(3), int64(1), object(16)
memory usage: 171.2+ KB

In [92]:
df.isnull().sum()

id                    0
season                0
city                 51
date                  0
match_type            0
player_of_match       5
venue                 0
team1                 0
team2                 0
toss_winner           0
toss_decision         0
winner                5
result                0
result_margin        19
target_runs           3
target_overs          3
super_over            0
method             1074
umpire1               0
umpire2               0
dtype: int64

In [93]:
df.duplicated().sum()

np.int64(0)

In [94]:
df = df.drop('result_margin',axis=1)

In [95]:
df = df.drop('method',axis=1)

In [96]:
df['target_runs'] = df['target_runs'].fillna(df['target_runs'].mode()[0])

In [97]:
df['target_overs'] = df['target_overs'].fillna(df['target_overs'].mode()[0])

In [98]:
df['city'] = df['city'].fillna('Unknown')

In [99]:
df = df.dropna(subset=['winner'])

In [100]:
df.isnull().sum()

id                 0
season             0
city               0
date               0
match_type         0
player_of_match    0
venue              0
team1              0
team2              0
toss_winner        0
toss_decision      0
winner             0
result             0
target_runs        0
target_overs       0
super_over         0
umpire1            0
umpire2            0
dtype: int64

In [101]:
df = df.drop(['player_of_match','result','target_runs','target_overs','umpire1','umpire2','date'],axis=1)

In [102]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1090 entries, 0 to 1094
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             1090 non-null   int64
 1   season         1090 non-null   object
 2   city           1090 non-null   object
 3   match_type     1090 non-null   object
 4   venue          1090 non-null   object
 5   team1          1090 non-null   object
 6   team2          1090 non-null   object
 7   toss_winner    1090 non-null   object
 8   toss_decision  1090 non-null   object
 9   winner         1090 non-null   object
 10  super_over     1090 non-null   object
dtypes: int64(1), object(10)
memory usage: 102.2+ KB

In [103]:
df.drop('id',axis=1,inplace=True)

In [104]:
team_name_map = {
    "Delhi Daredevils": "Delhi Capitals",
    "Deccan Chargers": "Sunrisers Hyderabad",   # optional (or keep separate)
    "Kings XI Punjab": "Punjab Kings",
    "Rising Pune Supergiant": "Rising Pune Supergiants",
    "Royal Challengers Bangalore": "Royal Challengers Bengaluru"
}

# Apply mapping to all team-related columns
team_columns = ["team1", "team2", "toss_winner", "winner"]

for col in team_columns:
    df[col] = df[col].replace(team_name_map)

In [105]:
# Total matches played by each team (team1 + team2 count)
team_matches = pd.concat([df["team1"], df["team2"]]).value_counts()

# Total wins by each team
team_wins = df["winner"].value_counts()

# Win rate = wins / matches
team_win_rate = (team_wins / team_matches).fillna(0)

# Add features to dataset
df["team1_win_rate"] = df["team1"].map(team_win_rate)
df["team2_win_rate"] = df["team2"].map(team_win_rate)

In [106]:
df["team1_toss_win"] = (df["toss_winner"] == df["team1"]).astype(int)

In [107]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
columns = ['super_over']
for col in columns:
    df[col] = le.fit_transform(df[col])

In [108]:
df['super_over'].value_counts()

super_over
0    1076
1      14
Name: count, dtype: int64

In [109]:
df['super_over'].dtype

dtype('int64')

In [110]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1090 entries, 0 to 1094
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   season          1090 non-null   object
 1   city            1090 non-null   object
 2   match_type      1090 non-null   object
 3   venue           1090 non-null   object
 4   team1           1090 non-null   object
 5   team2           1090 non-null   object
 6   toss_winner     1090 non-null   object
 7   toss_decision   1090 non-null   object
 8   winner          1090 non-null   object
 9   super_over      1090 non-null   int64
 10  team1_win_rate  1090 non-null   float64
 11  team2_win_rate  1090 non-null   float64
 12  team1_toss_win  1090 non-null   int64
dtypes: float64(2), int64(2), object(9)
memory usage: 119.2+ KB

In [111]:
df = pd.get_dummies(df,columns=['season','city','match_type','venue','team1','team2','toss_winner','toss_decision'],drop_first=True)

In [112]:
print(df.columns)

Index(['winner', 'super_over', 'team1_win_rate', 'team2_win_rate',
       'team1_toss_win', 'season_2009', 'season_2009/10', 'season_2011',
       'season_2012', 'season_2013',
       ...
       'toss_winner_Kolkata Knight Riders', 'toss_winner_Lucknow Super Giants',
       'toss_winner_Mumbai Indians', 'toss_winner_Pune Warriors',
       'toss_winner_Punjab Kings', 'toss_winner_Rajasthan Royals',
       'toss_winner_Rising Pune Supergiants',
       'toss_winner_Royal Challengers Bengaluru',
       'toss_winner_Sunrisers Hyderabad', 'toss_decision_field'],
      dtype='object', length=161)

In [113]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1090 entries, 0 to 1094
Columns: 161 entries, winner to toss_decision_field
dtypes: bool(156), float64(2), int64(2), object(1)
memory usage: 217.1+ KB

In [114]:
x = df.drop('winner',axis=1)
y = df['winner']

In [115]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [116]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [128]:
lr = LogisticRegression()
rf = RandomForestClassifier(random_state=42)
xgb = XGBClassifier()

In [129]:
lr.fit(x_train,y_train)
y_pred_lr = lr.predict(x_test)

In [130]:
lr.score(x_test,y_pred_lr)

1.0

In [131]:
print("Accuracy Score of Logistic Regression",accuracy_score(y_test,y_pred_lr))

Accuracy Score of Logistic Regression 0.5045871559633027

In [132]:
print("Confusiion Matrix of Logistic Regression",confusion_matrix(y_test,y_pred_lr))

Confusiion Matrix of Logistic Regression [[15  2  0  1  0  2  1  3  0  4  1  0  3  5]
 [ 0 10  0  0  0  0  0  2  1  2  2  0  0  3]
 [ 0  0  2  0  0  0  0  2  0  0  0  0  1  0]
 [ 1  2  0  3  0  1  0  0  0  0  1  0  1  0]
 [ 1  0  0  0  0  1  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0 10  0  3  0  2  1  0  3  3]
 [ 0  0  0  0  0  0  2  0  0  0  0  0  1  0]
 [ 2  3  0  0  0  0  0 15  0  3  1  0  1  1]
 [ 1  1  0  0  0  0  0  0  0  0  1  0  0  0]
 [ 0  3  0  0  0  2  1  0  0  9  1  1  3  0]
 [ 1  0  0  0  0  1  0  0  1  2 18  0  1  1]
 [ 0  0  0  0  0  1  0  1  0  0  0  2  0  0]
 [ 1  2  0  0  0  1  0  2  0  1  0  0 18  3]
 [ 0  1  0  0  0  0  0  3  0  0  1  0  2  6]]

In [133]:
print("Classification Report of Logistic Regression",classification_report(y_test,y_pred_lr))

Classification Report of Logistic Regression                              precision    recall  f1-score   support

        Chennai Super Kings       0.65      0.41      0.50        37
             Delhi Capitals       0.42      0.50      0.45        20
              Gujarat Lions       1.00      0.40      0.57         5
             Gujarat Titans       0.75      0.33      0.46         9
       Kochi Tuskers Kerala       0.00      0.00      0.00         2
      Kolkata Knight Riders       0.53      0.43      0.48        23
       Lucknow Super Giants       0.50      0.67      0.57         3
             Mumbai Indians       0.48      0.58      0.53        26
              Pune Warriors       0.00      0.00      0.00         3
               Punjab Kings       0.39      0.45      0.42        20
           Rajasthan Royals       0.67      0.72      0.69        25
    Rising Pune Supergiants       0.67      0.50      0.57         4
Royal Challengers Bengaluru       0.53      0.64      0.58        28
        Sunrisers Hyderabad       0.27      0.46      0.34        13

                   accuracy                           0.50       218
                  macro avg       0.49      0.44      0.44       218
               weighted avg       0.53      0.50      0.50       218

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [134]:
rf.fit(x_train,y_train)
y_pred_rf = rf.predict(x_test)

In [135]:
rf.score(x_test,y_pred_rf)

1.0

In [142]:
print("Accuracy Score of Random Forest",accuracy_score(y_test,y_pred_rf))

Accuracy Score of Random Forest 0.463302752293578

In [141]:
print("Confusiion Matrix of Random Forest",confusion_matrix(y_test,y_pred_rf))

Confusiion Matrix of Random Forest [[16  4  0  1  0  0  1  1  0  5  2  0  5  2]
 [ 1  6  1  0  0  0  0  2  1  3  2  0  0  4]
 [ 0  0  2  0  0  0  0  2  0  0  0  0  1  0]
 [ 0  2  0  4  0  1  0  0  0  0  2  0  0  0]
 [ 1  0  0  0  0  1  0  0  0  0  0  0  0  0]
 [ 2  0  0  0  0 13  0  3  0  1  0  0  0  4]
 [ 0  0  0  0  0  0  1  0  0  1  0  0  1  0]
 [ 4  2  0  0  0  1  0 14  0  2  2  0  0  1]
 [ 0  1  0  0  1  0  0  0  0  0  1  0  0  0]
 [ 1  1  0  0  0  2  1  1  0 10  1  0  3  0]
 [ 3  0  0  0  0  3  0  0  0  4 14  0  1  0]
 [ 0  0  1  0  0  1  0  0  0  0  0  1  0  1]
 [ 0  3  0  0  0  4  0  5  0  2  0  0 13  1]
 [ 0  1  0  0  0  0  2  1  0  1  0  0  1  7]]

In [138]:
print("Classification Report of Random Forest",classification_report(y_test,y_pred_rf))

Classification Report of Random Forest                              precision    recall  f1-score   support

        Chennai Super Kings       0.57      0.43      0.49        37
             Delhi Capitals       0.30      0.30      0.30        20
              Gujarat Lions       0.50      0.40      0.44         5
             Gujarat Titans       0.80      0.44      0.57         9
       Kochi Tuskers Kerala       0.00      0.00      0.00         2
      Kolkata Knight Riders       0.50      0.57      0.53        23
       Lucknow Super Giants       0.20      0.33      0.25         3
             Mumbai Indians       0.48      0.54      0.51        26
              Pune Warriors       0.00      0.00      0.00         3
               Punjab Kings       0.34      0.50      0.41        20
           Rajasthan Royals       0.58      0.56      0.57        25
    Rising Pune Supergiants       1.00      0.25      0.40         4
Royal Challengers Bengaluru       0.52      0.46      0.49        28
        Sunrisers Hyderabad       0.35      0.54      0.42        13

                   accuracy                           0.46       218
                  macro avg       0.44      0.38      0.39       218
               weighted avg       0.49      0.46      0.46       218

In [140]:
from sklearn.model_selection import RandomizedSearchCV
# Hyperparameter search space
param_dist = {
    "n_estimators": [100, 200, 300, 400, 500],
    "max_depth": [None, 10, 20, 30, 40, 50],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [1, 2, 4],
    "max_features": ["sqrt", "log2", None],
    "bootstrap": [True, False]
}

# Randomized Search
random_search = RandomizedSearchCV(
    estimator=rf,
    param_distributions=param_dist,
    n_iter=30,          # number of random combinations
    cv=5,               # cross validation
    verbose=2,
    random_state=42,
    n_jobs=-1
)

# Fit on training data
random_search.fit(x_train, y_train)

# Best parameters
print("Best Parameters:", random_search.best_params_)

# Best model
best_rf = random_search.best_estimator_

# Predictions
y_pred = best_rf.predict(x_test)

# Accuracy
print("Tuned Random Forest Accuracy:", accuracy_score(y_test, y_pred))

# Report
print(classification_report(y_test, y_pred))

Fitting 5 folds for each of 30 candidates, totalling 150 fits

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:813: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(

Best Parameters: {'n_estimators': 100, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': 'log2', 'max_depth': 40, 'bootstrap': True}
Tuned Random Forest Accuracy: 0.5275229357798165
                             precision    recall  f1-score   support

        Chennai Super Kings       0.68      0.35      0.46        37
             Delhi Capitals       0.33      0.30      0.32        20
              Gujarat Lions       0.00      0.00      0.00         5
             Gujarat Titans       0.50      0.11      0.18         9
       Kochi Tuskers Kerala       0.00      0.00      0.00         2
      Kolkata Knight Riders       0.53      0.78      0.63        23
       Lucknow Super Giants       1.00      0.33      0.50         3
             Mumbai Indians       0.51      0.77      0.62        26
              Pune Warriors       0.00      0.00      0.00         3
               Punjab Kings       0.52      0.60      0.56        20
           Rajasthan Royals       0.67      0.64      0.65        25
    Rising Pune Supergiants       1.00      0.25      0.40         4
Royal Challengers Bengaluru       0.57      0.57      0.57        28
        Sunrisers Hyderabad       0.38      0.85      0.52        13

                   accuracy                           0.53       218
                  macro avg       0.48      0.40      0.39       218
               weighted avg       0.54      0.53      0.50       218

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])